### PR TITLE
Patch: Update readme and fix broken links in docs

### PR DESCRIPTION
**Pull request by lwasser**
The docs build that i merged the other day was breaking because Strava deprecated the running races end point in November 2021. This PR just removes the links. but we should also remove the methods that access those endpoints in a pr because they are no longer available. See API changelog for more:

https://developers.strava.com/docs/changelog/

### CODE REVIEW

**Comment by lwasser** [comment]
@hozn this is one more - this is a tiny  pr that just removes two broken links in the docs that are caused due to strava removing those endpoints. please let me know if this is also ok to merge! thank you!

**Comment by yihong0618** [comment]
LGTM

**Comment by hozn** [comment]
Looks good here too. @lwasser appreciate you checking but feel free to make the decisions on these without asking.  I appreciate that you find this project useful and don't want to be in the way of you improving it however you see fit.

**Comment by lwasser** [comment]
ok thanks @hozn will merge this!

**Pull request merged**
