### PR TITLE
removed dependency on pip internal function

### PR DESCRIPTION
**Pull request by paulte**

### CODE REVIEW

**Comment by hozn** [comment]
Thank you -- that looks great.

**Comment by mscansian** [comment]
Is it possible to release a bugfix with this PR on PyPI? The current version is broken on pip 10.

**Comment by hozn** [comment]
Sure, I will do that now.

**Comment by hozn** [comment]
@mscansian , Ok, this is released in 0.9.2.

**Comment by mscansian** [comment]
Thanks :+1:

**Pull request merged**
